# Generated by Django 5.2.4 on 2025-08-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_remove_flight_details_flight_flight_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbooking',
            name='seat_number',
        ),
    ]
