# Generated by Django 5.2.4 on 2025-08-14 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_flight_booking_flight_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight_details',
            name='flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('seat_number', models.IntegerField()),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.flight')),
            ],
        ),
        migrations.DeleteModel(
            name='Flight_booking',
        ),
        migrations.DeleteModel(
            name='Flight_details',
        ),
    ]
